version: '3'

services:

  backend:
    build: ./backend
    container_name: backend-smartphone-manager
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    ports:
      - 3001:3001
    env_file:
      ./backend/.env
    networks:
      - smartphone-manager-network

  db:
    image: postgres:16.2
    restart: always
    container_name: db-smartphone-manager
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
    networks:
      - smartphone-manager-network

  frontend:
    build: ./frontend
    container_name: frontend-smartphone-manager
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    networks:
      - smartphone-manager-network

networks:
  smartphone-manager-network:
    driver: bridge
